"""empty message

Revision ID: 20306a3ea0dc
Revises: 
Create Date: 2019-12-05 22:16:11.119952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20306a3ea0dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('a_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('a_name', sa.String(length=20), nullable=False),
    sa.Column('a_passwd', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('a_id'),
    sa.UniqueConstraint('a_name')
    )
    op.create_table('subject',
    sa.Column('sub_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sub_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('sub_id')
    )
    op.create_table('teacher',
    sa.Column('t_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('t_name', sa.String(length=20), nullable=True),
    sa.Column('t_pwd', sa.String(length=50), nullable=True),
    sa.Column('t_pic', sa.String(length=50), nullable=True),
    sa.Column('t_sex', sa.Integer(), nullable=True),
    sa.Column('t_subject', sa.Integer(), nullable=True),
    sa.Column('t_university', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['t_subject'], ['subject.sub_id'], ),
    sa.PrimaryKeyConstraint('t_id')
    )
    op.create_table('grade',
    sa.Column('g_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('g_name', sa.String(length=20), nullable=True),
    sa.Column('g_create_time', sa.DATETIME(), nullable=True),
    sa.Column('g_mainteacher', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['g_mainteacher'], ['teacher.t_id'], ),
    sa.PrimaryKeyConstraint('g_id'),
    sa.UniqueConstraint('g_name')
    )
    op.create_table('grade_teacher',
    sa.Column('g_id', sa.Integer(), nullable=True),
    sa.Column('t_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['g_id'], ['grade.g_id'], ),
    sa.ForeignKeyConstraint(['t_id'], ['teacher.t_id'], )
    )
    op.create_table('student',
    sa.Column('s_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('s_name', sa.String(length=20), nullable=True),
    sa.Column('s_pwd', sa.String(length=50), nullable=True),
    sa.Column('s_pic', sa.String(length=50), nullable=True),
    sa.Column('s_sex', sa.Integer(), nullable=True),
    sa.Column('s_age', sa.Integer(), nullable=True),
    sa.Column('s_birthday', sa.Date(), nullable=True),
    sa.Column('s_father', sa.String(length=10), nullable=True),
    sa.Column('s_mother', sa.String(length=10), nullable=True),
    sa.Column('s_fatherphone', sa.String(length=20), nullable=True),
    sa.Column('s_motherphone', sa.String(length=20), nullable=True),
    sa.Column('s_addr', sa.String(length=80), nullable=True),
    sa.Column('grade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.g_id'], ),
    sa.PrimaryKeyConstraint('s_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('grade_teacher')
    op.drop_table('grade')
    op.drop_table('teacher')
    op.drop_table('subject')
    op.drop_table('admin')
    # ### end Alembic commands ###
